# Generated by Django 5.1.1 on 2024-10-22 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Meteo", "0002_alter_codeinse_code"),
    ]

    operations = [
        migrations.RenameField(
            model_name="codeinse",
            old_name="ville",
            new_name="town",
        ),
    ]
