# Generated by Django 5.1.1 on 2024-11-02 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Meteo", "0003_rename_ville_codeinse_town"),
    ]

    operations = [
        migrations.RenameField(
            model_name="codeinse",
            old_name="town",
            new_name="ville",
        ),
    ]
