# Generated by Django 5.1.1 on 2024-11-02 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Meteo", "0004_rename_town_codeinse_ville"),
    ]

    operations = [
        migrations.RenameField(
            model_name="codeinse",
            old_name="ville",
            new_name="town",
        ),
    ]
